// sd.config.android.mjs — Style Dictionary v5 configuration (ESM) for Android.
// Run `make tokens-android` (or `npm run tokens:android`) to regenerate:
//   android/FitMeDesignTokens.kt          (Jetpack Compose)
//   android/res/values/colors.xml         (Android resources)
//   android/res/values/dimens.xml         (Android resources)
//
// Companion to sd.config.mjs (the iOS Swift pipeline). Same source of truth
// (design-tokens/tokens.json), same hand-rolled-format philosophy: rather than
// depend on Style Dictionary's built-in `compose`/`android` transform groups
// (whose transform names drifted across the v3→v5 migration and assumed
// rem-input tokens, not FitMe's raw-pixel scale), we read each token's original
// value + path directly and emit exactly the Kotlin/XML we want. This is what
// supersedes the old, non-functional design-tokens/config-android.json.
//
// Token-type handling:
//   color       (49) → Compose Color(0xAARRGGBB) + XML <color>#AARRGGBB</color>
//                       (handles both #hex and rgba(r,g,b,a) source values)
//   spacing      (8) → Dp / <dimen>Ndp</dimen>
//   borderRadius(10) → Dp / <dimen>Ndp</dimen>
//   dimension   (16) → Dp / <dimen>Ndp</dimen>   (size.* + layout.* + shadow.*)
//   opacity      (3) → Compose Float (Compose-tier only)
//   motion       (6) → Compose duration-ms Int + easing comment (Compose-tier only)
//   typography  (16) → semantic iOS text-style strings, NOT numeric point sizes;
//                       emitted as a reference comment that points at the MD3
//                       mapping in docs/design-system/android-token-mapping.md.

import StyleDictionary from "style-dictionary";

const NS = "com.fitme.designsystem";

// ── Colour conversion ────────────────────────────────────────────────────────
function parseColorToARGB(raw) {
  const v = String(raw).trim();
  if (v.startsWith("rgba(") || v.startsWith("rgb(")) {
    const nums = v.replace(/rgba?\(/, "").replace(")", "").split(",").map((s) => s.trim());
    const r = parseInt(nums[0], 10);
    const g = parseInt(nums[1], 10);
    const b = parseInt(nums[2], 10);
    const a = nums[3] !== undefined ? Math.round(parseFloat(nums[3]) * 255) : 255;
    return { a, r, g, b };
  }
  let hex = v.replace("#", "");
  if (hex.length === 3) hex = hex.split("").map((c) => c + c).join("");
  if (hex.length === 6) {
    return { a: 255, r: parseInt(hex.slice(0, 2), 16), g: parseInt(hex.slice(2, 4), 16), b: parseInt(hex.slice(4, 6), 16) };
  }
  if (hex.length === 8) {
    return { a: parseInt(hex.slice(0, 2), 16), r: parseInt(hex.slice(2, 4), 16), g: parseInt(hex.slice(4, 6), 16), b: parseInt(hex.slice(6, 8), 16) };
  }
  throw new Error(`Unparseable color value: ${raw}`);
}
const h2 = (n) => n.toString(16).padStart(2, "0").toUpperCase();
const composeColor = (v) => { const { a, r, g, b } = parseColorToARGB(v); return `Color(0x${h2(a)}${h2(r)}${h2(g)}${h2(b)})`; };
const xmlColor = (v) => { const { a, r, g, b } = parseColorToARGB(v); return `#${h2(a)}${h2(r)}${h2(g)}${h2(b)}`; };

// ── Name conversion ──────────────────────────────────────────────────────────
// Compose member: drop the category segment, camel-join the rest.
//   ['color','brand','primary'] → brandPrimary ; ['shadow','card','radius'] → cardRadius
const memberName = (path) =>
  path.slice(1).map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1))).join("");
// XML resource: snake_case of the given path segments.
const snake = (parts) => parts.join("_").replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();

const num = (t) => Number(t.original.value);
const isDimType = (t) => t.type === "spacing" || t.type === "borderRadius" || t.type === "dimension";

// ── Compose Kotlin format ────────────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: "compose/fitme-tokens",
  format: ({ dictionary }) => {
    const now = new Date().toISOString().slice(0, 10);
    const all = dictionary.allTokens;
    const ofType = (type) => all.filter((t) => t.type === type);
    const dimsWithRoot = (root) => all.filter((t) => t.type === "dimension" && t.path[0] === root);
    const L = [
      `// android/FitMeDesignTokens.kt`,
      `// AUTO-GENERATED by \`make tokens-android\` on ${now} — do not edit by hand.`,
      `// Source: design-tokens/tokens.json   Mapping: docs/design-system/android-token-mapping.md`,
      `package ${NS}`,
      ``,
      `import androidx.compose.ui.graphics.Color`,
      `import androidx.compose.ui.unit.Dp`,
      `import androidx.compose.ui.unit.dp`,
      ``,
    ];

    L.push(`object FitMeColors {`);
    ofType("color").forEach((t) => {
      const c = t.comment ? ` // ${t.comment}` : "";
      L.push(`    val ${memberName(t.path)} = ${composeColor(t.original.value)}${c}`);
    });
    L.push(`}`, ``);

    const dpObject = (title, tokens) => {
      L.push(`object ${title} {`);
      tokens.forEach((t) => L.push(`    val ${memberName(t.path)}: Dp = ${num(t)}.dp`));
      L.push(`}`, ``);
    };
    dpObject("FitMeSpacing", ofType("spacing"));
    dpObject("FitMeRadius", ofType("borderRadius"));
    dpObject("FitMeSize", dimsWithRoot("size"));
    dpObject("FitMeLayout", dimsWithRoot("layout"));
    dpObject("FitMeElevation", dimsWithRoot("shadow"));

    L.push(`object FitMeOpacity {`);
    ofType("opacity").forEach((t) => L.push(`    const val ${memberName(t.path)} = ${num(t)}f`));
    L.push(`}`, ``);

    L.push(`object FitMeMotion {`);
    L.push(`    // Durations in milliseconds; easing noted for AnimationSpec selection.`);
    ofType("motion").forEach((t) => {
      const m = t.original.value;
      L.push(`    const val ${memberName(t.path)}Ms = ${Math.round(Number(m.duration) * 1000)} // ${m.easing}`);
    });
    L.push(`}`, ``);

    L.push(`// Typography tokens are semantic iOS text-style references`);
    L.push(`// (e.g. "largeTitle/bold/rounded"), not numeric point sizes. They map to`);
    L.push(`// the Material 3 type scale — see docs/design-system/android-token-mapping.md §2.`);
    ofType("typography").forEach((t) => L.push(`//   ${memberName(t.path)} → ${t.original.value}`));
    L.push(``);

    return L.join("\n");
  },
});

// ── Android XML formats ──────────────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: "androidXml/fitme-colors",
  format: ({ dictionary }) => {
    const now = new Date().toISOString().slice(0, 10);
    const L = [
      `<?xml version="1.0" encoding="utf-8"?>`,
      `<!-- AUTO-GENERATED by \`make tokens-android\` on ${now} — do not edit by hand. Source: design-tokens/tokens.json -->`,
      `<resources>`,
    ];
    dictionary.allTokens
      .filter((t) => t.type === "color")
      .forEach((t) => L.push(`    <color name="${snake(t.path.slice(1))}">${xmlColor(t.original.value)}</color>`));
    L.push(`</resources>`, ``);
    return L.join("\n");
  },
});

StyleDictionary.registerFormat({
  name: "androidXml/fitme-dimens",
  format: ({ dictionary }) => {
    const now = new Date().toISOString().slice(0, 10);
    const L = [
      `<?xml version="1.0" encoding="utf-8"?>`,
      `<!-- AUTO-GENERATED by \`make tokens-android\` on ${now} — do not edit by hand. Source: design-tokens/tokens.json -->`,
      `<resources>`,
    ];
    dictionary.allTokens
      .filter(isDimType)
      .forEach((t) => L.push(`    <dimen name="${snake(t.path)}">${num(t)}dp</dimen>`));
    L.push(`</resources>`, ``);
    return L.join("\n");
  },
});

export default {
  source: ["design-tokens/tokens.json"],
  platforms: {
    compose: {
      transforms: ["attribute/cti", "name/camel"],
      buildPath: "android/",
      files: [{ destination: "FitMeDesignTokens.kt", format: "compose/fitme-tokens" }],
    },
    androidXml: {
      transforms: ["attribute/cti", "name/camel"],
      buildPath: "android/res/values/",
      files: [
        { destination: "colors.xml", format: "androidXml/fitme-colors" },
        { destination: "dimens.xml", format: "androidXml/fitme-dimens" },
      ],
    },
  },
};
