// sd.config.mjs — Style Dictionary v5 configuration (ESM)
// Run `make tokens` to regenerate FitTracker/DesignSystem/DesignTokens.swift
// Requires: npm install (installs style-dictionary as dev dep)
//
// Migrated from sd.config.js (v3) on 2026-06-08. v5 is ESM-only; the v3→v5
// API renames are: require→import, module.exports→export default,
// matcher→filter, transformer→transform, formatter→format, sync
// .extend().buildAllPlatforms()→async new StyleDictionary()+build (handled by
// the CLI in the Makefile), name/cti/camel→name/camel. The transform/format
// function BODIES are unchanged — same hex→RGB math, same line emission — so
// the generated DesignTokens.swift is byte-identical to the v3 output.

import StyleDictionary from "style-dictionary";

// Custom transform: convert hex colors to Swift Color(red:green:blue:) or rgba
StyleDictionary.registerTransform({
  name: "color/swift",
  type: "value",
  filter: (token) => token.type === "color",
  transform: (token) => {
    const v = token.value;
    // Pass rgba strings through as-is (documented in output)
    if (v.startsWith("rgba(")) return v;
    // Convert hex to RGB floats
    const hex = v.replace("#", "");
    const r = (parseInt(hex.slice(0, 2), 16) / 255).toFixed(3);
    const g = (parseInt(hex.slice(2, 4), 16) / 255).toFixed(3);
    const b = (parseInt(hex.slice(4, 6), 16) / 255).toFixed(3);
    return `Color(red: ${r}, green: ${g}, blue: ${b})`;
  },
});

// Custom format: emit a Swift enum
StyleDictionary.registerFormat({
  name: "swift/fittracker-tokens",
  format: ({ dictionary }) => {
    const now = new Date().toISOString().slice(0, 10);
    const lines = [
      `// FitTracker/DesignSystem/DesignTokens.swift`,
      `// AUTO-GENERATED by \`make tokens\` on ${now} — do not edit by hand.`,
      `// Source: design-tokens/tokens.json`,
      `// Regenerate: run \`make tokens\` in the repo root.`,
      `import SwiftUI`,
      ``,
      `// MARK: - Color tokens`,
      `enum DesignTokenColor {`,
    ];

    // Colors
    dictionary.allTokens
      .filter((t) => t.type === "color")
      .forEach((t) => {
        const name = t.path.join("_").replace(/-/g, "_");
        const desc = t.comment ? ` // ${t.comment}` : "";
        lines.push(`    static let ${name} = "${t.value}"${desc}`);
      });

    lines.push(`}`);
    lines.push(``);
    lines.push(`// MARK: - Spacing tokens (strict 4pt grid)`);
    lines.push(`enum DesignTokenSpacing {`);

    dictionary.allTokens
      .filter((t) => t.type === "spacing")
      .forEach((t) => {
        const name = t.path[t.path.length - 1];
        lines.push(`    static let ${name}: CGFloat = ${t.value}`);
      });

    lines.push(`}`);
    lines.push(``);
    lines.push(`// MARK: - Radius tokens`);
    lines.push(`enum DesignTokenRadius {`);

    dictionary.allTokens
      .filter((t) => t.type === "borderRadius")
      .forEach((t) => {
        const name = t.path[t.path.length - 1];
        lines.push(`    static let ${name}: CGFloat = ${t.value}`);
      });

    lines.push(`}`);
    lines.push(``);

    return lines.join("\n") + "\n";
  },
});

export default {
  source: ["design-tokens/tokens.json"],
  platforms: {
    swift: {
      transforms: ["attribute/cti", "name/camel", "color/swift"],
      buildPath: "FitTracker/DesignSystem/",
      files: [
        {
          destination: "DesignTokens.swift",
          format: "swift/fittracker-tokens",
          options: {
            outputReferences: false,
          },
        },
      ],
    },
  },
};
