// sd.config.js — Style Dictionary v5 configuration
// Run `make tokens` (or `npm run tokens`) to regenerate
// FitTracker/DesignSystem/DesignTokens.swift.
//
// v5 migration (2026-06-03): switched from side-effect registration
// (`StyleDictionary.registerTransform / .registerFormat`) to the v5
// inline `hooks` config. This makes the config self-contained: no
// `require("style-dictionary")` needed, so the CLI can be invoked from
// any spawn context (npx, local node_modules, npm-script, etc.) without
// a module-resolution mismatch.
//
// Other v5 deltas from the previous v3 config:
//   - `matcher` → `filter`
//   - `transformer` → `transform`
//   - `formatter` → `format`
//   - `name/cti/*` transforms renamed to `name/*` (cti namespace dropped)
//   - `attribute/cti` is now auto-applied; no longer in transforms list

module.exports = {
  source: ["design-tokens/tokens.json"],

  hooks: {
    transforms: {
      "color/swift": {
        type: "value",
        filter: (token) => token.type === "color",
        transform: (token) => {
          const v = token.value;
          // Pass rgba strings through as-is (documented in output)
          if (v.startsWith("rgba(")) return v;
          // Convert hex to RGB floats
          const hex = v.replace("#", "");
          const r = (parseInt(hex.slice(0, 2), 16) / 255).toFixed(3);
          const g = (parseInt(hex.slice(2, 4), 16) / 255).toFixed(3);
          const b = (parseInt(hex.slice(4, 6), 16) / 255).toFixed(3);
          return `Color(red: ${r}, green: ${g}, blue: ${b})`;
        },
      },
    },

    formats: {
      "swift/fittracker-tokens": ({ dictionary }) => {
        const now = new Date().toISOString().slice(0, 10);
        const lines = [
          `// FitTracker/DesignSystem/DesignTokens.swift`,
          `// AUTO-GENERATED by \`make tokens\` on ${now} — do not edit by hand.`,
          `// Source: design-tokens/tokens.json`,
          `// Regenerate: run \`make tokens\` in the repo root.`,
          `import SwiftUI`,
          ``,
          `// MARK: - Color tokens`,
          `enum DesignTokenColor {`,
        ];

        dictionary.allTokens
          .filter((t) => t.type === "color")
          .forEach((t) => {
            const name = t.path.join("_").replace(/-/g, "_");
            const desc = t.comment ? ` // ${t.comment}` : "";
            lines.push(`    static let ${name} = "${t.value}"${desc}`);
          });

        lines.push(`}`);
        lines.push(``);
        lines.push(`// MARK: - Spacing tokens (strict 4pt grid)`);
        lines.push(`enum DesignTokenSpacing {`);

        dictionary.allTokens
          .filter((t) => t.type === "spacing")
          .forEach((t) => {
            const name = t.path[t.path.length - 1];
            lines.push(`    static let ${name}: CGFloat = ${t.value}`);
          });

        lines.push(`}`);
        lines.push(``);
        lines.push(`// MARK: - Radius tokens`);
        lines.push(`enum DesignTokenRadius {`);

        dictionary.allTokens
          .filter((t) => t.type === "borderRadius")
          .forEach((t) => {
            const name = t.path[t.path.length - 1];
            lines.push(`    static let ${name}: CGFloat = ${t.value}`);
          });

        lines.push(`}`);
        lines.push(``);

        return lines.join("\n") + "\n";
      },
    },
  },

  platforms: {
    swift: {
      // v5: dropped `attribute/cti` (auto-applied); `name/cti/camel` → `name/camel`
      transforms: ["name/camel", "color/swift"],
      buildPath: "FitTracker/DesignSystem/",
      files: [
        {
          destination: "DesignTokens.swift",
          format: "swift/fittracker-tokens",
          options: {
            outputReferences: false,
          },
        },
      ],
    },
  },
};
