// android/FitMeDesignTokens.kt
// AUTO-GENERATED by `make tokens-android` on 2026-06-17 — do not edit by hand.
// Source: design-tokens/tokens.json   Mapping: docs/design-system/android-token-mapping.md
package com.fitme.designsystem

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object FitMeColors {
    val brandPrimary = Color(0xFFFA8F40)
    val brandSecondary = Color(0xFF8AC7FF)
    val brandWarmSoft = Color(0xFFFFE3BA)
    val brandWarm = Color(0xFFFFC78A)
    val brandCoolSoft = Color(0xFFDFF3FF)
    val brandCool = Color(0xFFBAE3FF)
    val backgroundAppPrimary = Color(0xFFDFF3FF)
    val backgroundAppSecondary = Color(0xFFF0FAFF)
    val backgroundAppTint = Color(0xFFBAE3FF)
    val backgroundAppWarmTint = Color(0xFFFFE3BA)
    val backgroundAuthTop = Color(0xFF0A140F)
    val backgroundAuthMiddle = Color(0xFF102419)
    val backgroundAuthBottom = Color(0xFF05100A)
    val textPrimary = Color(0xD6000000)
    val textSecondary = Color(0x9E000000)
    val textTertiary = Color(0x8C000000)
    val textInversePrimary = Color(0xF0FFFFFF)
    val textInverseSecondary = Color(0xC2FFFFFF)
    val textInverseTertiary = Color(0x8AFFFFFF)
    val surfacePrimary = Color(0xB8FFFFFF)
    val surfaceSecondary = Color(0x94FFFFFF)
    val surfaceTertiary = Color(0x61FFFFFF)
    val surfaceElevated = Color(0xEBFFFFFF)
    val surfaceMaterialLight = Color(0x38FFFFFF)
    val surfaceMaterialStrong = Color(0x57FFFFFF)
    val surfaceInverse = Color(0xD1000000)
    val borderStrong = Color(0x8AFFFFFF)
    val borderSubtle = Color(0x4DFFFFFF)
    val borderHairline = Color(0x14000000)
    val statusSuccess = Color(0xFF34C759)
    val statusWarning = Color(0xFFFF9500)
    val statusError = Color(0xFFFF3B30)
    val accentRecovery = Color(0xFF5AC8FA)
    val accentSleep = Color(0xFFBF5AF2)
    val accentAchievement = Color(0xFFFFD60A)
    val chartBody = Color(0xFFFFC78A)
    val chartCardio = Color(0xFF5AC8FA)
    val chartSleep = Color(0xFFBF5AF2)
    val chartAchievement = Color(0xFFFFD60A)
    val chartProgress = Color(0xFF8AC7FF)
    val chartNutritionFat = Color(0xFF996025)
    val chartWeight = Color(0xFFFFA94D)
    val chartHrv = Color(0xFF32D74B)
    val chartHeartRate = Color(0xFFFF6961)
    val chartActivity = Color(0xFFFFCE5C)
    val selectionActive = Color(0xD6FFFFFF)
    val selectionInactive = Color(0x6BFFFFFF)
    val cardColor = Color(0x14000000)
    val ctaColor = Color(0x47FA8F40)
}

object FitMeSpacing {
    val xxxSmall: Dp = 4.dp
    val xxSmall: Dp = 8.dp
    val xSmall: Dp = 12.dp
    val small: Dp = 16.dp
    val medium: Dp = 20.dp
    val large: Dp = 24.dp
    val xLarge: Dp = 32.dp
    val xxLarge: Dp = 40.dp
}

object FitMeRadius {
    val micro: Dp = 4.dp
    val xSmall: Dp = 8.dp
    val small: Dp = 12.dp
    val medium: Dp = 16.dp
    val card: Dp = 16.dp
    val button: Dp = 20.dp
    val large: Dp = 24.dp
    val xLarge: Dp = 28.dp
    val sheet: Dp = 32.dp
    val authSheet: Dp = 36.dp
}

object FitMeSize {
    val ctaHeight: Dp = 52.dp
    val touchTargetLarge: Dp = 48.dp
    val iconBadge: Dp = 26.dp
    val progressBarHeight: Dp = 4.dp
    val indicatorDot: Dp = 8.dp
    val tabBarClearance: Dp = 56.dp
}

object FitMeLayout {
    val chartHeight: Dp = 158.dp
    val emptyStateMinHeight: Dp = 128.dp
    val chipMinWidth: Dp = 128.dp
    val chipIdealWidth: Dp = 144.dp
    val chipMaxWidth: Dp = 168.dp
    val dotSize: Dp = 8.dp
}

object FitMeElevation {
    val cardRadius: Dp = 10.dp
    val cardYOffset: Dp = 4.dp
    val ctaRadius: Dp = 12.dp
    val ctaYOffset: Dp = 4.dp
}

object FitMeOpacity {
    const val disabled = 0.15f
    const val subtle = 0.12f
    const val hover = 0.08f
}

object FitMeMotion {
    // Durations in milliseconds; easing noted for AnimationSpec selection.
    const val stepTransitionMs = 300 // easeInOut
    const val quickInteractionMs = 200 // easeOut
    const val pressFeedbackMs = 160 // easeOut
    const val selectionChangeMs = 180 // easeOut
    const val pageTransitionMs = 200 // easeInOut
    const val progressFillMs = 600 // easeOut
}

// Typography tokens are semantic iOS text-style references
// (e.g. "largeTitle/bold/rounded"), not numeric point sizes. They map to
// the Material 3 type scale — see docs/design-system/android-token-mapping.md §2.
//   hero → largeTitle/bold/rounded
//   pageTitle → title2/bold/rounded
//   titleStrong → title3/bold/rounded
//   titleMedium → title3/semibold/rounded
//   sectionTitle → headline/semibold/rounded
//   body → body/medium/rounded
//   bodyRegular → body/regular/rounded
//   callout → callout/medium/rounded
//   subheading → subheadline/regular/rounded
//   caption → caption/regular/rounded
//   captionStrong → caption/semibold/rounded
//   eyebrow → caption/bold/rounded
//   chip → footnote/semibold/rounded
//   monoMetric → title3/bold/monospaced
//   monoLabel → caption2/semibold/monospaced
//   button → body/semibold/rounded
