// FitTracker/DesignSystem/DesignTokens.swift
// AUTO-GENERATED by `make tokens` on 2026-04-19 — do not edit by hand.
// Source: design-tokens/tokens.json
// Regenerate: run `make tokens` in the repo root.
import SwiftUI

// MARK: - Color tokens
enum DesignTokenColor {
    static let color_brand_primary = "Color(red: 0.980, green: 0.561, blue: 0.251)"
    static let color_brand_secondary = "Color(red: 0.541, green: 0.780, blue: 1.000)"
    static let color_brand_warmSoft = "Color(red: 1.000, green: 0.890, blue: 0.729)"
    static let color_brand_warm = "Color(red: 1.000, green: 0.780, blue: 0.541)"
    static let color_brand_coolSoft = "Color(red: 0.875, green: 0.953, blue: 1.000)"
    static let color_brand_cool = "Color(red: 0.729, green: 0.890, blue: 1.000)"
    static let color_background_appPrimary = "Color(red: 0.875, green: 0.953, blue: 1.000)"
    static let color_background_appSecondary = "Color(red: 0.941, green: 0.980, blue: 1.000)"
    static let color_background_appTint = "Color(red: 0.729, green: 0.890, blue: 1.000)"
    static let color_background_appWarmTint = "Color(red: 1.000, green: 0.890, blue: 0.729)"
    static let color_background_authTop = "Color(red: 0.039, green: 0.078, blue: 0.059)"
    static let color_background_authMiddle = "Color(red: 0.063, green: 0.141, blue: 0.098)"
    static let color_background_authBottom = "Color(red: 0.020, green: 0.063, blue: 0.039)"
    static let color_text_primary = "rgba(0,0,0,0.84)"
    static let color_text_secondary = "rgba(0,0,0,0.62)"
    static let color_text_tertiary = "rgba(0,0,0,0.55)"
    static let color_text_inversePrimary = "rgba(255,255,255,0.94)"
    static let color_text_inverseSecondary = "rgba(255,255,255,0.76)"
    static let color_text_inverseTertiary = "rgba(255,255,255,0.54)"
    static let color_surface_primary = "rgba(255,255,255,0.72)"
    static let color_surface_secondary = "rgba(255,255,255,0.58)"
    static let color_surface_tertiary = "rgba(255,255,255,0.38)"
    static let color_surface_elevated = "rgba(255,255,255,0.92)"
    static let color_surface_materialLight = "rgba(255,255,255,0.22)"
    static let color_surface_materialStrong = "rgba(255,255,255,0.34)"
    static let color_surface_inverse = "rgba(0,0,0,0.82)"
    static let color_border_strong = "rgba(255,255,255,0.54)"
    static let color_border_subtle = "rgba(255,255,255,0.30)"
    static let color_border_hairline = "rgba(0,0,0,0.08)"
    static let color_status_success = "Color(red: 0.204, green: 0.780, blue: 0.349)"
    static let color_status_warning = "Color(red: 1.000, green: 0.584, blue: 0.000)"
    static let color_status_error = "Color(red: 1.000, green: 0.231, blue: 0.188)"
    static let color_accent_recovery = "Color(red: 0.353, green: 0.784, blue: 0.980)"
    static let color_accent_sleep = "Color(red: 0.749, green: 0.353, blue: 0.949)"
    static let color_accent_achievement = "Color(red: 1.000, green: 0.839, blue: 0.039)"
    static let color_chart_body = "Color(red: 1.000, green: 0.780, blue: 0.541)"
    static let color_chart_cardio = "Color(red: 0.353, green: 0.784, blue: 0.980)"
    static let color_chart_sleep = "Color(red: 0.749, green: 0.353, blue: 0.949)"
    static let color_chart_achievement = "Color(red: 1.000, green: 0.839, blue: 0.039)"
    static let color_chart_progress = "Color(red: 0.541, green: 0.780, blue: 1.000)"
    static let color_chart_nutritionFat = "Color(red: 0.600, green: 0.376, blue: 0.145)"
    static let color_chart_weight = "Color(red: 1.000, green: 0.663, blue: 0.302)"
    static let color_chart_hrv = "Color(red: 0.196, green: 0.843, blue: 0.294)"
    static let color_chart_heartRate = "Color(red: 1.000, green: 0.412, blue: 0.380)"
    static let color_chart_activity = "Color(red: 1.000, green: 0.808, blue: 0.361)"
    static let color_selection_active = "rgba(255,255,255,0.84)"
    static let color_selection_inactive = "rgba(255,255,255,0.42)"
    static let shadow_card_color = "rgba(0,0,0,0.08)"
    static let shadow_cta_color = "rgba(250,143,64,0.28)"
}

// MARK: - Spacing tokens (strict 4pt grid)
enum DesignTokenSpacing {
    static let xxxSmall: CGFloat = 4
    static let xxSmall: CGFloat = 8
    static let xSmall: CGFloat = 12
    static let small: CGFloat = 16
    static let medium: CGFloat = 20
    static let large: CGFloat = 24
    static let xLarge: CGFloat = 32
    static let xxLarge: CGFloat = 40
}

// MARK: - Radius tokens
enum DesignTokenRadius {
    static let micro: CGFloat = 4
    static let xSmall: CGFloat = 8
    static let small: CGFloat = 12
    static let medium: CGFloat = 16
    static let card: CGFloat = 16
    static let button: CGFloat = 20
    static let large: CGFloat = 24
    static let xLarge: CGFloat = 28
    static let sheet: CGFloat = 32
    static let authSheet: CGFloat = 36
}

