// FitTracker/DesignSystem/DesignTokens.swift
// AUTO-GENERATED by `make tokens` — do not edit by hand.
// Source of truth: design-tokens/tokens.json (Figma Variables export)
// Regenerate: run `make tokens` in the repo root.
// CI gate: `make tokens-check` fails if this file is out of sync.
//
// This file is a pipeline artifact — it is NOT used directly by SwiftUI views.
// Views import AppTheme.swift (AppColor / AppText / AppSpacing / AppRadius).
// DesignTokens.swift exists so CI can detect Figma ↔ Swift drift.

import SwiftUI

// MARK: - Color tokens (mirrors AppPalette + AppColor)
enum DesignTokenColor {
    static let brandPrimary    = AppPalette.orange500       // #FA8F40
    static let brandSecondary  = AppPalette.blue500         // #8AC7FF
    static let brandWarmSoft   = AppPalette.orange50        // #FFE3BA
    static let brandWarm       = AppPalette.orange100       // #FFC78A
    static let brandCoolSoft   = AppPalette.blue50          // #DFF3FF
    static let brandCool       = AppPalette.blue200         // #BAE3FF

    static let textPrimary     = AppColor.Text.primary      // rgba(0,0,0,0.84)
    static let textSecondary   = AppColor.Text.secondary    // rgba(0,0,0,0.62)
    static let textTertiary    = AppColor.Text.tertiary     // rgba(0,0,0,0.55) — WCAG AA

    static let statusSuccess   = AppPalette.green           // #34C759
    static let statusWarning   = AppPalette.amber           // #FF9500
    static let statusError     = AppPalette.red             // #FF3B30

    static let accentCyan      = AppPalette.cyan            // #5AC8FA
    static let accentPurple    = AppPalette.purple          // #BF5AF2
    static let accentGold      = AppPalette.gold            // #FFD60A
}

// MARK: - Spacing tokens (mirrors AppSpacing — strict 4pt grid)
enum DesignTokenSpacing {
    static let xxxSmall: CGFloat = 4
    static let xxSmall:  CGFloat = 8
    static let xSmall:   CGFloat = 12
    static let small:    CGFloat = 16
    static let medium:   CGFloat = 20
    static let large:    CGFloat = 24
    static let xLarge:   CGFloat = 32
    static let xxLarge:  CGFloat = 40
}

// MARK: - Radius tokens (mirrors AppRadius)
enum DesignTokenRadius {
    static let xSmall:    CGFloat = 8
    static let small:     CGFloat = 12
    static let medium:    CGFloat = 16
    static let large:     CGFloat = 24
    static let xLarge:    CGFloat = 28
    static let sheet:     CGFloat = 32
    static let authSheet: CGFloat = 36
}
