#!/usr/bin/env node
// scripts/check-tokens.js — CI gate: verify DesignTokens.swift is up to date
// Usage: node scripts/check-tokens.js
// Fails with exit code 1 if the committed DesignTokens.swift doesn't match
// what `make tokens` would generate from the current tokens.json.

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const TARGET = path.join(__dirname, "../FitTracker/DesignSystem/DesignTokens.swift");

// Read committed file (strip auto-generated date line for comparison)
const committed = fs.readFileSync(TARGET, "utf8")
  .replace(/\/\/ AUTO-GENERATED by `make tokens` on \d{4}-\d{2}-\d{2}/, "// AUTO-GENERATED DATE-STRIPPED");

// Generate fresh output into a temp file
const tmp = "/tmp/DesignTokens-check.swift";
try {
  execSync(`node -e "
    const SD = require('./node_modules/style-dictionary');
    const config = require('./sd.config.js');
    // Override destination to tmp
    config.platforms.swift.buildPath = '/tmp/';
    const sd = SD.extend(config);
    sd.buildAllPlatforms();
  "`, { stdio: "inherit" });
} catch (e) {
  console.error("❌  make tokens failed to run. Is node_modules installed?");
  process.exit(1);
}

if (!fs.existsSync(tmp)) {
  console.error("❌  Temp output not found at", tmp);
  process.exit(1);
}

const generated = fs.readFileSync(tmp, "utf8")
  .replace(/\/\/ AUTO-GENERATED by `make tokens` on \d{4}-\d{2}-\d{2}/, "// AUTO-GENERATED DATE-STRIPPED");

if (committed === generated) {
  console.log("✅  DesignTokens.swift is in sync with tokens.json");
  process.exit(0);
} else {
  console.error("❌  DesignTokens.swift is OUT OF SYNC with tokens.json.");
  console.error("    Run `make tokens` and commit the result.");
  process.exit(1);
}
