#!/usr/bin/env node
// scripts/check-tokens.js — CI gate: verify DesignTokens.swift is up to date
// Regenerates DesignTokens.swift in place, compares with git, then restores.

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const TARGET = path.join(__dirname, "../FitTracker/DesignSystem/DesignTokens.swift");

// Save the committed version
const committed = fs.readFileSync(TARGET, "utf8");

// Regenerate via make tokens
try {
  execSync("make tokens", { stdio: "inherit", cwd: path.join(__dirname, "..") });
} catch (e) {
  console.error("❌  make tokens failed:", e.message);
  process.exit(1);
}

// Read the freshly generated version
const generated = fs.readFileSync(TARGET, "utf8");

// Restore the committed version immediately
fs.writeFileSync(TARGET, committed, "utf8");

// Strip date lines for comparison
function strip(s) {
  return s.replace(/\/\/ AUTO-GENERATED by `make tokens` on \d{4}-\d{2}-\d{2}/, "DATE");
}

if (strip(committed) === strip(generated)) {
  console.log("✅  DesignTokens.swift is in sync with tokens.json");
  process.exit(0);
} else {
  console.error("❌  DesignTokens.swift is OUT OF SYNC with tokens.json.");
  console.error("    Run `make tokens` and commit the result.");
  process.exit(1);
}
