#!/usr/bin/env node
// scripts/check-tokens.js — CI gate: verify DesignTokens.swift is up to date
// Usage: node scripts/check-tokens.js
// Fails with exit code 1 if the committed DesignTokens.swift doesn't match
// what `make tokens` would generate from the current tokens.json.

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const TARGET = path.join(__dirname, "../FitTracker/DesignSystem/DesignTokens.swift");
const TMP = "/tmp/DesignTokens.swift";

// Strip the auto-generated date line so comparison ignores timestamp differences
function stripDate(content) {
  return content.replace(
    /\/\/ AUTO-GENERATED by `make tokens` on \d{4}-\d{2}-\d{2}/,
    "// AUTO-GENERATED DATE-STRIPPED"
  );
}

// Read committed file
const committed = stripDate(fs.readFileSync(TARGET, "utf8"));

// Generate fresh output by running make tokens to a temp location.
// We copy sd.config.js behavior but output to /tmp/.
try {
  if (fs.existsSync(TMP)) fs.unlinkSync(TMP);

  // Use make tokens but redirect output — simplest approach is to
  // generate in place, copy, then restore.
  const backup = fs.readFileSync(TARGET, "utf8");
  execSync("make tokens", { stdio: "inherit" });
  const freshGenerated = fs.readFileSync(TARGET, "utf8");

  // Restore the committed version
  fs.writeFileSync(TARGET, backup, "utf8");

  // Compare
  const generated = stripDate(freshGenerated);

  if (committed === generated) {
    console.log("✅  DesignTokens.swift is in sync with tokens.json");
    process.exit(0);
  } else {
    console.error("❌  DesignTokens.swift is OUT OF SYNC with tokens.json.");
    console.error("    Run `make tokens` and commit the result.");
    process.exit(1);
  }
} catch (e) {
  console.error("❌  make tokens failed to run:", e.message);
  process.exit(1);
}
